- hosts: localhost
  become: true
  tasks:
    - name: Install ZSH
      apt:
        name: zsh
        state: present
      tags: &tags_for_zsh_tasks
        - install
        - productivity
        - dotfiles
        - zsh

    - name: Change shell to zsh
      shell: chsh -s $(which zsh)
      tags: *tags_for_zsh_tasks

    - name: Check that the .oh-my-zsh directory exists
      stat:
        path: /home/trev/.oh-my-zsh
      register: oh_my_stats
      tags: *tags_for_zsh_tasks

    - name: Install Oh-My-Zsh
      shell: |
        curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
      tags: *tags_for_zsh_tasks
      when: oh_my_stats.stat.exists == False
      become_user: trev
      environment:
        HOME: /home/trev

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "/home/trev/.oh-my-zsh/plugins/zsh-autosuggestions"
      tags: *tags_for_zsh_tasks
      become_user: trev

    - name: Ensure we're running as trev user
      command: whoami
      register: whoami_output
      become_user: trev

    - name: Debug whoami
      debug:
        msg: "Current user is: {{ whoami_output.stdout }}"

    - name: Debug working directory
      command: pwd
      register: pwd_output
      become_user: trev

    - name: Debug pwd
      debug:
        msg: "Current directory is: {{ pwd_output.stdout }}"

    - name: Install nvm
      become_user: trev
      ansible.builtin.shell: |
        export HOME=/home/trev
        export NVM_DIR="$HOME/.nvm"
        mkdir -p $NVM_DIR
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
        echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
        echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc
        echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.zshrc
      args:
        executable: /bin/bash
        chdir: "/home/trev"
        creates: "/home/trev/.nvm/nvm.sh"
      environment:
        HOME: /home/trev

    - name: Install node
      become_user: trev
      shell: |
        . /home/trev/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "/home/trev"
        creates: "/home/trev/.nvm/versions/{{ item }}"
      loop:
        - 20.10.0
      environment:
        HOME: /home/trev
