- name: Install nvm
  become: true
  become_user: "{{ current_user }}"
  ansible.builtin.shell: |
    export HOME="/home/{{ current_user }}"
    export NVM_DIR="$HOME/.nvm"
    mkdir -p $NVM_DIR
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.zshrc
  args:
    executable: /bin/bash
    chdir: "/home/{{ current_user }}"
    creates: "/home/{{ current_user }}/.nvm/nvm.sh"
  environment:
    HOME: "/home/{{ current_user }}"

- name: Install node
  become: true
  become_user: "{{ current_user }}"
  shell: |
    . /home/{{ current_user }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "/home/{{ current_user }}"
    creates: "/home/{{ current_user }}/.nvm/versions/node/v{{ item }}"
  loop:
    - 20.10.0
  environment:
    HOME: "/home/{{ current_user }}"

- name: Set default node version
  become: true
  become_user: "{{ current_user }}"
  shell: |
    . /home/{{ current_user }}/.nvm/nvm.sh && nvm alias default {{ item }}
  args:
    executable: /bin/bash
    chdir: "/home/{{ current_user }}"
  loop:
    - 20.10.0
  environment:
    HOME: "/home/{{ current_user }}"