- name: Install nvm
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.shell: |
    export HOME="{{ ansible_env.HOME }}"
    export NVM_DIR="$HOME/.nvm"
    mkdir -p $NVM_DIR
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.zshrc
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Install node
  become: true
  become_user: "{{ ansible_user_id }}"
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ item }}"
  loop:
    - 20.10.0
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Set default node version
  become: true
  become_user: "{{ ansible_user_id }}"
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
  loop:
    - 20.10.0
  environment:
    HOME: "{{ ansible_env.HOME }}"