- name: Install nvm
  become_user: trev
  ansible.builtin.shell: |
    export HOME=/home/trev
    export NVM_DIR="$HOME/.nvm"
    mkdir -p $NVM_DIR
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.zshrc
  args:
    executable: /bin/bash
    chdir: "/home/trev"
    creates: "/home/trev/.nvm/nvm.sh"
  environment:
    HOME: /home/trev

- name: Install node
  become_user: trev
  shell: |
    . /home/trev/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "/home/trev"
    creates: "/home/trev/.nvm/versions/{{ item }}"
  loop:
    - 20.10.0
  environment:
    HOME: /home/trev
