- name: Ensure .ssh directory exists for current user
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Copy SSH public key to the .ssh folder for current user
  copy:
    src: "{{ playbook_dir }}/.ssh/id_rsa.pub"
    dest: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
    mode: '0644'

- name: Copy SSH private key to the .ssh folder for current user
  copy:
    src: "{{ playbook_dir }}/.ssh/id_rsa"
    dest: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    mode: '0600'
    decrypt: yes

- name: Debug current user and group
  debug:
    msg: "Current user: {{ ansible_user_id }}, Current group: {{ ansible_user_gid }}"

- name: Debug SSH directory contents
  shell: ls -la {{ ansible_env.HOME }}/.ssh
  register: ssh_contents

- name: Display SSH directory contents
  debug:
    var: ssh_contents.stdout_lines