- name: Install ZSH
  apt:
    name: zsh
    state: present
  become: true

- name: Change shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Check that the .oh-my-zsh directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_stats

- name: Install Oh-My-Zsh
  shell: |
    curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  become: true
  become_user: "{{ ansible_user_id }}"
  args:
    executable: /bin/bash

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  # become: true
  become_user: "{{ ansible_user_id }}"